context:
    navigationItems:
        - label: Meets
          href: /meets
        - label: About
          href: /about
        - label: Rules
          href: /rules
        - label: Blog
          href: http://blog.severnbronies.co.uk/