context:
    title: Privacy policy
    image: //placeponi.es/1200/300
    date: 6th July 2016; 9:14am
    content: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vitae porttitor nibh. In hac habitasse platea dictumst. Suspendisse ut ante et tellus faucibus ultricies eget vel ante. Aliquam pharetra odio lacus. Duis feugiat elit quis luctus sollicitudin. Morbi turpis felis, imperdiet nec elit vitae, hendrerit porta lorem. Sed ac mi ut massa ornare egestas.

