context:
    columns: 
        - header: Column One
          content: This is some copy in the table
        - header: Column Two
          content: This is yet more copy in the table.
        - header: Column Three
          content: Say hello.
        - header: Column Four
          content: This copy is really quite long and is much longer than the other copy. What will happen?!