context: 
    avatars: 
        - //placeponi.es/100/100/9
        - //placeponi.es/100/100/8
    meetRunner: Kim, Coaldust
    meetType: Games Bronies Play
    meetStart: 16th July 2016; 12:00pm
    meetEnd: 6:00pm
    meetLocation: Forbidden Planet, Clifton Heights, Triangle West, Bristol, BS8 1EJ 