context:
    name: Kim
    email: kim@severnbronies.co.uk
    biography: An eccentric and neurotic bookworm, Kim is obviously the ideal candidate to operate in the fast-paced, stressful world of brony meets.
    avatar: //placeponi.es/300/300